---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
      - python
      - css
  csslint:
    enabled: true
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      max-statements:
        enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.module"
  - "**.py"
exclude_paths:
- .git/
- tests/
