language: generic
sudo: required
dist: trusty
install:
    - sudo ./scripts/install-dev-environment.sh
    - sudo chown -R $USER .
    - sudo chgrp -R live-status ~ .
script:
    /opt/live-status-website/bin/nosetests
