# this file was generated by scripts/install-dev-environment.sh
live-status-website:
    root: /vagrant
    dev_environment: True
    settings:
        api_token: yMhyfJoNI2fTyp3rStK1A0B6u8ZhMJUJ60M3y0qB
        database: mysql://root@127.0.0.1/live_status
