"""empty message

Revision ID: c3faad69c152
Revises: None
Create Date: 2016-06-05 07:39:52.804131

"""

# revision identifiers, used by Alembic.
revision = 'c3faad69c152'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.Column('health', sa.SmallInteger(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('lifetime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_update')
    ### end Alembic commands ###
