#!/bin/sh -ex

# This installs a fully functional dev environment on the system. Specifically, it...
#
#     * Installs a mysql server and creates a fresh database
#     * Installs and configures the salt minion
#     * Runs state.highstate
#     * Initializes the database
#
# THIS SCRIPT IS TO BE USED FOR PRIVATE DEVELOPMENT ENVIRONMENTS ONLY.

ROOT=$(dirname $(dirname $(readlink -f $0)))

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get install -yq mysql-server
mysql -u root -e 'create database live_status'

sh $ROOT/scripts/install-salt-minion.sh

cat > $ROOT/salt/pillar/live-status.sls << PillarData
# this file was generated by scripts/install-dev-environment.sh
live-status:
    root: $ROOT
    dev_environment: True
    settings:
        api_token: yMhyfJoNI2fTyp3rStK1A0B6u8ZhMJUJ60M3y0qB
        database: mysql://root@127.0.0.1/live_status
PillarData

salt-call --local state.highstate

cd $ROOT && LIVE_STATUS_SETTINGS=/opt/live-status/settings.json /opt/live-status/bin/python -m app db upgrade
